---
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 2023.1.0
  version_files:
  - project.json
  - ignition/script-python/incendium/version/code.py
